### ISSUE TITLE
Empty results from array

### ISSUE THREAD

**Issue by vaguiners** [p3nt4/RunDLL.Net#5]
After many tries, i managet to get the right command to get from GetOSDEntries https://github.com/spencerhakim/RTSSSharedMemoryNET/blob/master/RTSSSharedMemoryNET/OSD.cpp

But the result is empty
Command: rundll32.exe Rundll.Net.dll,main C:\Users\xxx\Desktop\test\RTSSSharedMemoryNET.dll RTSSSharedMemoryNET.OSD GetAppEntries

Console:

######################   [runDll.Net]   ######################
[Assembly]   C:\Users\xxx\Desktop\test\RTSSSharedMemoryNET.dll
[Class]      RTSSSharedMemoryNET.OSD
[Method]     GetAppEntries
[Arguments]
######################  Method Result   ######################
RTSSSharedMemoryNET.AppEntry[]

**Comment by p3nt4** [comment]
The method returns an array, which is printed as "RTSSSharedMemoryNET.AppEntry[]". You might need to edit the DLL slightly to print the array as a string with the formatting you like.
